## Twitch data API test

## load libraries
library(httr)
library(jsonlite)

## SETUP ####
## Go to Twitch dev site to set up app and get client id
## https://dev.twitch.tv/dashboard 
## clientid: store in Renviron
## clientsecret: store in Renviron

## QUERIES ####
## example
## get top games (current viewers): https://dev.twitch.tv/docs/api/reference/#get-top-games
## example code from site:
# curl -H 'Client-ID: <client id>' \
# -X GET 'https://api.twitch.tv/helix/games/top'

## Get top X games, based on current viewers ####
## BUT...no numbers, just ordered list :(
## Default list size is 20 -> actually 19 games because 1 field for pagination
## Max list size = 100
## To get desired number, use 'query=list(first=X)' and set X at desired number + 1
get_top_games <- GET('https://api.twitch.tv/helix/games/top',
                 add_headers('Client-ID'=Sys.getenv('TWITCH_CLIENT_ID')),
                 query=list(first=26)) ## gets top 25 + pagination field
get_top_games_content <- content(get_top_games)
## convert list outupt to JSON
gtgc_json <- toJSON(get_top_games_content)
## convert JSON to organized data in data frame
top_games <- fromJSON(gtgc_json, simplifyDataFrame=TRUE) ## simplifyDataFrame not needed
## game list data frame
top_games_list <- top_games$data

## get subsequent page using the cursor value in pagination field of prev query
## gets the next X (first=X) games after previous query
## 'after' parameter in query list determines pagination
get_top_games2 <- GET('https://api.twitch.tv/helix/games/top',
                     add_headers('Client-ID'=Sys.getenv('TWITCH_CLIENT_ID')),
                     query=list(first=5,
                                after=get_top_games_content$pagination[[1]]))
get_top_games2_content <- content(get_top_games2)
## convert list outupt to JSON
gtgc_json <- toJSON(get_top_games2_content)
## convert JSON to organized data in data frame
top_games2 <- fromJSON(gtgc_json, simplifyDataFrame=TRUE) ## simplifyDataFrame not needed
## game info data frame
top_games2_list <- top_games2$data


## Get specified game(s) - also no data ####
## https://dev.twitch.tv/docs/api/reference/#get-games
get_game <- GET('https://api.twitch.tv/helix/games?id=493057',
                 add_headers('Client-ID'=Sys.getenv('TWITCH_CLIENT_ID')))
get_game_content <- content(get_game)

## Get videos for specific game ####
## lots of videos with view counts (no other info)
get_video_game <- GET('https://api.twitch.tv/helix/videos?game_id=493057',
                      add_headers('Client-ID'='9h60z4dmgz6seveyc6vjpqx98jemak'))
get_vg_content <- content(get_video_game)

#### GAME DATA ####
## Need authentication
## - appears to be designed only for those who register their games with company account
## - full set of game metrics available
## 

## get token
## OAuth implicit code flow
## https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-implicit-code-flow

## example from reference
# GET https://id.twitch.tv/oauth2/authorize
# ?client_id=
#   &redirect_uri=<your registered redirect URI>
#   &response_type=<type>
#   &scope=<space-separated list of scopes>
  
twitch_auth <- GET('https://id.twitch.tv/oauth2/authorize?',
            query=list(client_id=Sys.getenv('TWITCH_CLIENT_ID'),
                       redirect_uri='http://localhost',
                       response_type='token',
                       scope='analytics:read:games'))
## get url generated by above
twitch_auth$request$url
## paste into browser, agree
## paste resulting URL here (will be page error but URL has info):
# http://localhost/#access_token=<TOKEN WILL APPEAR HERE>&scope=analytics%3Aread%3Agames&token_type=bearer

## use token to make request
## https://dev.twitch.tv/docs/api/reference/#get-game-analytics
#curl -H 'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y' \
#-X GET 'https://api.twitch.tv/helix/analytics/games?type=overview_v2&game_id=493057&started_at=2018-01-01T00:00:00Z&ended_at=2018-03-01T00:00:00Z'

## DENIED: 'Forbidden', 'User Has No Access to Any Games'
twitch_gamedata <- GET('https://api.twitch.tv/helix/analytics/games?type=overview_v2&game_id=511224&started_at=2019-01-01T00:00:00Z&ended_at=2019-02-01T00:00:00Z',
  add_headers('Authorization'='Bearer <TOKEN FROM URL')
)
twitch_gamedata_content <- content(twitch_gamedata)
## Error message
twitch_gamedata_content


